version: 2
updates:
  - package-ecosystem: "github-actions"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    schedule:
      interval: "daily"
